# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-23 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('user_detail', models.CharField(max_length=500)),
            ],
        ),
    ]
